name: "godot-ci export"
on: 
  push:
  workflow_dispatch:

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: export game
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: "https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_linux_headless.64.zip"
          godot_export_templates_download_url: "https://downloads.tuxfamily.org/godotengine/3.5.3/Godot_v3.5.3-stable_export_templates.tpz"
          relative_project_path: ./
          use_godot_3: true
          relative_export_path: build/web

      - name: List folder
        run: ls -la